/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bookMenu = new javax.swing.JMenu();
        addTrainerMenuItem = new javax.swing.JMenuItem();
        updateDeleteTrainer = new javax.swing.JMenuItem();
        TrainerListMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addMemberMenuItem = new javax.swing.JMenuItem();
        updateDeleteMembersMenuItem = new javax.swing.JMenuItem();
        membersAllMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - GMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym-Home.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        bookMenu.setText("Trainer");
        bookMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookMenuActionPerformed(evt);
            }
        });

        addTrainerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        addTrainerMenuItem.setText("Add Trainer");
        addTrainerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrainerMenuItemActionPerformed(evt);
            }
        });
        bookMenu.add(addTrainerMenuItem);

        updateDeleteTrainer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteTrainer.setText("Update Or Delete Trainer");
        updateDeleteTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteTrainerActionPerformed(evt);
            }
        });
        bookMenu.add(updateDeleteTrainer);

        TrainerListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        TrainerListMenuItem.setText("All Trainer");
        TrainerListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerListMenuItemActionPerformed(evt);
            }
        });
        bookMenu.add(TrainerListMenuItem);

        jMenuBar1.add(bookMenu);

        jMenu2.setText("Members");

        addMemberMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        addMemberMenuItem.setText("Add Member");
        addMemberMenuItem.setToolTipText("");
        addMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(addMemberMenuItem);

        updateDeleteMembersMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteMembersMenuItem.setText("Update Or Delete Members");
        updateDeleteMembersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteMembersMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(updateDeleteMembersMenuItem);

        membersAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        membersAllMenuItem.setText("Members List");
        membersAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membersAllMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(membersAllMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bookMenuActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addTrainerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrainerMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddTrainer().setVisible(true);
        
    }//GEN-LAST:event_addTrainerMenuItemActionPerformed

    private void addMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddMember().setVisible(true);
    }//GEN-LAST:event_addMemberMenuItemActionPerformed

    private void membersAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersAllMenuItemActionPerformed
        // TODO add your handling code here:
        new View.MembersList().setVisible(true);
    }//GEN-LAST:event_membersAllMenuItemActionPerformed

    private void TrainerListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerListMenuItemActionPerformed
        // TODO add your handling code here:
        new View.TrainerList().setVisible(true);
    }//GEN-LAST:event_TrainerListMenuItemActionPerformed

    private void updateDeleteMembersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteMembersMenuItemActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteMembers().setVisible(true);
    }//GEN-LAST:event_updateDeleteMembersMenuItemActionPerformed

    private void updateDeleteTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteTrainerActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteTrainer().setVisible(true);
    }//GEN-LAST:event_updateDeleteTrainerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem TrainerListMenuItem;
    private javax.swing.JMenuItem addMemberMenuItem;
    private javax.swing.JMenuItem addTrainerMenuItem;
    private javax.swing.JMenu bookMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem membersAllMenuItem;
    private javax.swing.JMenuItem updateDeleteMembersMenuItem;
    private javax.swing.JMenuItem updateDeleteTrainer;
    // End of variables declaration//GEN-END:variables
}
